# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of bun

name: Check (bun)

on:
  workflow_dispatch:

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-bun:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.0.0]
        # See Bun releases at https://github.com/oven-sh/bun/releases

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Use Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test src

      - name: Build application
        run: bun run build

      - name: Run typecheck
        run: bun run typecheck

      - name: Check linting
        run: bun run lint

      - name: Check formatting
        run: bun run format:check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
