name: Playwright Tests

# TODO: Fix this workflow #
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

jobs:
  e2e-test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [latest]
        bun-version: [latest]

    steps:
      - uses: actions/checkout@v3

      - name: Fetch main branch
        run: git fetch origin main:main -u

      - name: Use Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Get installed Playwright version
        id: playwright-version
        run: bun scripts/get-playwright-version.mjs

      - name: Cache Playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ${{ github.workspace }}/.pw-browsers
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install dependencies
        run: |
          rm bun.lock
          bun install

      - name: Build Git Truck
        run: bun run build

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.pw-browsers

      - name: Run Playwright tests
        run: bun test:e2e
        env:
          PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.pw-browsers

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.os }}-node-${{ matrix.node }}
          path: playwright-report/
          retention-days: 30
