name: Release
permissions: {}
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false
      - name: Setup Bun
        uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun ci --ignore-scripts
      - name: Run tests
        run: bun test src
  publish:
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false
      - name: Setup Bun
        uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979
        with:
          bun-version: latest
      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
      - name: Update NPM
        run: npm install -g npm@11.16.0
      - name: Install dependencies
        run: bun ci --ignore-scripts
      - run: bun run build
      - name: Create Release or Publish
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba
        with:
          # publish: bunx changeset publish
          publish: npm stage publish --provenance --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ""
    environment: npm
